### ISSUE TITLE
PHP download.php warnings

### ISSUE THREAD

**Issue by garthvs** [HandyPlugins/handyplugins-paddlepress#24]
I am using PaddlePress Pro 2.1.1

Environment is:

Wordpress 6.4.2
Apache 2.4.52
PHP FPM 8.1

My server logs are full of hundreds of the following warnings / errors:

[proxy_fcgi:error] [pid 383599:tid 140503605532224] [remote X.X.X.X:37005] AH01071: Got error 'PHP message: PHP Warning:  Attempt to read property "post_status" on null in /var/www/website.com/wp-content/plugins/paddlepress-pro/includes/download.php on line 112

[proxy_fcgi:error] [pid 383599:tid 140503672772160] [remote X.X.X.X:37308] AH01071: Got error ':  Attempt to read property "post_parent" on null in /var/www/website.com/wp-content/plugins/paddlepress-pro/includes/download.php on line 287

**Comment by mustafauysal** [comment]
Hi @garthvs,

Thanks for reporting the issue; I will check it.

**Comment by mustafauysal** [comment]
Hi @garthvs,

The issues you mentioned have been resolved in version `2.1.2`. I recommend updating your PaddlePress PRO to the latest version for these fixes. Also, please note that this repository is dedicated to the free version of the plugin. For any assistance with the premium version, don't hesitate to contact me at support[at]handyplugins.co.

Cheers,
